### ISSUE TITLE
Question : boiler running values

### ISSUE THREAD

**Issue by iomax** [komw/ariston-remotethermo-client#1]
Hi,
do you know if there any options to get running values too, like the values we can show through menu 8.x by full boiler menu ?

**Comment by komw** [comment]
Unfortunately no. I didn't found that ariston returns those values through APi. It seems that they only sends a values which you can found on website, and nothing else.

If you would like to get values from 8.X menu, you should use a EBUS converter and get it directly from boiler bus. You can find a working configuration for Ebusd deamon here -> (https://github.com/komw/ariston-bus-bridgenet-ebusd)
But there is only a few options, I didn't found how to get values from menu 8.2.* (especially the power of flame) I found that one value seems to be related to % power of flame, but sometimes it shows some strange values.

**Comment by iomax** [comment]
Thanks for the really fast reply and for your work … let me to inform that it works on Caffoteaux Mira Advance Link without issues and/or mods needs.
Ariston provide a Remote Assistance Services where the all the boiler data and menu are available to the technicians remotely so I’d think more to account level issue ( final user instead of “technicians” ) than a missing API feature.
Anyway, indeed I was thinking about the ebusd deamon but I need to study it deeply and still missing some info like HW, or PCB, availability as the real difference between various hw interface by ebusd wiki pages.
Off course, even the “Ariston” ebus2 ver was a issue but your configuration solved it :-)

Thanks

Ciao

**Comment by komw** [comment]
Agree with you. I saw on some russian forums, that Ariston provides a technical support for boilers, and them post some screenshots of website to manage it. 
Unfortunately, I don't have access to it. 
So next, I've decided to use a ebus solution. I;m using a ebus converter which PCB you can buy at https://forum.fhem.de/ Guys from time to time order a pack of PCB's from factory, and sell it through forum (PCB and elements costs me around 35EUR).
Ariston bus bridge net is very similar to ebus protocol, but it has some differences, but with my configuration is seems to work pretty stable. I'm using this solution for around 4 months, and it work without major problems.

Regards!
